title: Bluecup
description: "Redcup: An awesome Theme for Jekyll"

url: http://jeanlescut.github.io/redcup/
port: 3000
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: kramdown

google_analytics: #

owner:
  name: Jean Lescut 
  disqus_shortname: nadjetey
  twitter: _nadjetey
