title: Redcup
description: "Redcup: An awesome Theme for Jekyll"

url: http://nadjetey.github.io/redcup/
pygments: true

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Nii Adjetey Sowah
  disqus_shortname: nadjetey
  twitter: _nadjetey
  
