title: RedCup
description: "Redcup: An awesome Theme for Jekyll"
<<<<<<< HEAD
url: http://nadjetey.github.io/redcup
port: 3000
highlighter: pygments
=======

url: http://nadjetey.github.io/redcup/
pygments: true
>>>>>>> url

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Nii Adjetey Sowah
  disqus_shortname: nadjetey
  twitter: _nadjetey

